name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  test-input: #input id
    description: 'my first action test'
    required: true
    default: 'Basic Input'
outputs:
  time:
    description: 'Run time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-input }}
