name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  test-input:
    description: 'my first action test'
    required: true
    default: 'Basic Input'
outputs:
  time: # id of output
    description: 'Out put current time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.test-input }}
