name: First action
on:
  [push]
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: check
        uses: actions/checkout@v3
      - name: output
        uses: ./
        with:
          test-input: 'My name'