name: First action
on:
  [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  check:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install robotframework
      - id: step1
        run: robot -o NONE -l NONE -r NONE testsuites/t.robot > "$GITHUB_OUTPUT"
        #run: echo "test=hello" >> "$GITHUB_OUTPUT"
  output:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - env:
          OUT: ${{ needs.check.outputs.output1 }}
        run: echo "$OUT" >> "$GITHUB_STEP_SUMMARY"
