on: [push]

jobs:
  test_input_job:
    runs-on: ubuntu-latest
    name: Test Input job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: my repo's action test
        uses: ./
        id: myinput
        with:
          test-input: 'Try this input first!'
          test-input-one: 'How come this not worked'
      - name: Print current time to Summary
        run: echo "Current Time is ${{ steps.myinput.outputs.time }}" >> "$GITHUB_STEP_SUMMARY"
